[package]
name = "vm_xml_tool"
version = "0.1.0"
edition = "2024"

[dependencies]
serde-xml-rs = "0.8.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.145"
quick-xml = { version = "0.38.4", features = ["serialize", "serde-types"] }